### ISSUE TITLE
Unable to build on Ubuntu 19.10

### ISSUE THREAD

**Issue by AndrewBarfield** [RileyHL/gr-scan#6]
I _think_ this problem is related to using GNU Radio 3.8.0.0... Not certain though.

Machine:

- OS: Ubuntu 19.10 eoan
- Kernel: x86_64 Linux 5.3.0-23-generic
- Shell: bash 5.0.3
- CPU: Intel Core i7-8809G @ 8x 4.2GHz [27.8°C]
- GPU: AMD VEGAM (DRM 3.33.0, 5.3.0-23-generic, LLVM 9.0.0)
- RAM: 3043MiB / 32035MiB

Software:

- GNU Radio version 3.8.0.0
- Companion 3.8.0.0 (Python 3.7.5rc1)
- g++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

The first time I ran `make` I got:
```
g++  -O3 -march=native -fomit-frame-pointer -DVERSION="\"gr-scan 20180115\"" -Wall -std=c++11 *.cpp -o gr-scan -lgnuradio-filter -lgnuradio-blocks -lgnuradio-pmt -lgnuradio-fft -lgnuradio-runtime -lgnuradio-osmosdr -lboost_system -lstdc++fs 
/usr/bin/ld: /tmp/ccXW3K1f.o: undefined reference to symbol '_ZN7log4cpp8Appender29AppenderMapStorageInitializerD1Ev'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/liblog4cpp.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:35: gr-scan] Error 1
```
Apparently there is a long-standing bug/issue between GNU Radio and log4cpp. To resolve the problem I added **-llog4cpp** to LDLIBS:
```
LDLIBS = -llog4cpp -lgnuradio-filter -lgnuradio-blocks -lgnuradio-pmt -lgnuradio-fft -lgnuradio-runtime -lgnuradio-osmosdr -lboost_system -lstdc++fs
```
Now I'm getting:
```
g++  -O3 -march=native -fomit-frame-pointer -DVERSION="\"gr-scan 20180115\"" -Wall -std=c++11 *.cpp -o gr-scan -llog4cpp -lgnuradio-filter -lgnuradio-blocks -lgnuradio-pmt -lgnuradio-fft -lgnuradio-runtime -lgnuradio-osmosdr -lboost_system -lstdc++fs 
/usr/bin/ld: /tmp/ccg47hpw.o: in function `gr::basic_block::has_msg_port(boost::shared_ptr<pmt::pmt_base>)':
main.cpp:(.text._ZN2gr11basic_block12has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11basic_block12has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x4b): undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: main.cpp:(.text._ZN2gr11basic_block12has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11basic_block12has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x6c): undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: main.cpp:(.text._ZN2gr11basic_block12has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11basic_block12has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x9d): undefined reference to `pmt::dict_has_key(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: /tmp/ccg47hpw.o: in function `gr::basic_block::has_msg_handler(boost::shared_ptr<pmt::pmt_base>)':
main.cpp:(.text._ZN2gr11basic_block15has_msg_handlerEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11basic_block15has_msg_handlerEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x4b): undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: main.cpp:(.text._ZN2gr11basic_block15has_msg_handlerEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11basic_block15has_msg_handlerEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x6f): undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: /tmp/ccg47hpw.o: in function `gr::hier_block2::message_port_is_hier_out(boost::shared_ptr<pmt::pmt_base>)':
main.cpp:(.text._ZN2gr11hier_block224message_port_is_hier_outEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11hier_block224message_port_is_hier_outEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x40): undefined reference to `pmt::list_has(boost::shared_ptr<pmt::pmt_base>, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: /tmp/ccg47hpw.o: in function `gr::hier_block2::message_port_is_hier_in(boost::shared_ptr<pmt::pmt_base>)':
main.cpp:(.text._ZN2gr11hier_block223message_port_is_hier_inEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11hier_block223message_port_is_hier_inEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x40): undefined reference to `pmt::list_has(boost::shared_ptr<pmt::pmt_base>, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: /tmp/ccg47hpw.o: in function `gr::hier_block2::message_port_is_hier(boost::shared_ptr<pmt::pmt_base>)':
main.cpp:(.text._ZN2gr11hier_block220message_port_is_hierEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11hier_block220message_port_is_hierEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x7e): undefined reference to `pmt::list_has(boost::shared_ptr<pmt::pmt_base>, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: main.cpp:(.text._ZN2gr11hier_block220message_port_is_hierEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11hier_block220message_port_is_hierEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x101): undefined reference to `pmt::list_has(boost::shared_ptr<pmt::pmt_base>, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: /tmp/ccg47hpw.o: in function `gr::hier_block2::has_msg_port(boost::shared_ptr<pmt::pmt_base>)':
main.cpp:(.text._ZN2gr11hier_block212has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11hier_block212has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0xb8): undefined reference to `pmt::list_has(boost::shared_ptr<pmt::pmt_base>, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: /tmp/ccg47hpw.o:main.cpp:(.text._ZN2gr11hier_block212has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11hier_block212has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x13f): more undefined references to `pmt::list_has(boost::shared_ptr<pmt::pmt_base>, boost::shared_ptr<pmt::pmt_base> const&)' follow
/usr/bin/ld: /tmp/ccg47hpw.o: in function `gr::hier_block2::has_msg_port(boost::shared_ptr<pmt::pmt_base>)':
main.cpp:(.text._ZN2gr11hier_block212has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11hier_block212has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x207): undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: main.cpp:(.text._ZN2gr11hier_block212has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11hier_block212has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x229): undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: main.cpp:(.text._ZN2gr11hier_block212has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE[_ZN2gr11hier_block212has_msg_portEN5boost10shared_ptrIN3pmt8pmt_baseEEE]+0x25b): undefined reference to `pmt::dict_has_key(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: /tmp/ccg47hpw.o: in function `TopBlock::TopBlock(double, double, double, double, double, double, double, unsigned int, double, double, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
main.cpp:(.text._ZN8TopBlockC2EdddddddjdddRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN8TopBlockC5EdddddddjdddRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x34b): undefined reference to `gr::blocks::file_meta_sink::make(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double, double, gr::blocks::gr_file_types, bool, unsigned long, boost::shared_ptr<pmt::pmt_base>, bool)'
/usr/bin/ld: /tmp/ccg47hpw.o: in function `std::_Rb_tree<boost::shared_ptr<pmt::pmt_base>, std::pair<boost::shared_ptr<pmt::pmt_base> const, boost::function<void (boost::shared_ptr<pmt::pmt_base>)> >, std::_Select1st<std::pair<boost::shared_ptr<pmt::pmt_base> const, boost::function<void (boost::shared_ptr<pmt::pmt_base>)> > >, pmt::comparator, std::allocator<std::pair<boost::shared_ptr<pmt::pmt_base> const, boost::function<void (boost::shared_ptr<pmt::pmt_base>)> > > >::_M_get_insert_unique_pos(boost::shared_ptr<pmt::pmt_base> const&)':
main.cpp:(.text._ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE24_M_get_insert_unique_posERS6_[_ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE24_M_get_insert_unique_posERS6_]+0x4e): undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: main.cpp:(.text._ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE24_M_get_insert_unique_posERS6_[_ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE24_M_get_insert_unique_posERS6_]+0x89): undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: /tmp/ccg47hpw.o: in function `std::_Rb_tree_iterator<std::pair<boost::shared_ptr<pmt::pmt_base> const, boost::function<void (boost::shared_ptr<pmt::pmt_base>)> > > std::_Rb_tree<boost::shared_ptr<pmt::pmt_base>, std::pair<boost::shared_ptr<pmt::pmt_base> const, boost::function<void (boost::shared_ptr<pmt::pmt_base>)> >, std::_Select1st<std::pair<boost::shared_ptr<pmt::pmt_base> const, boost::function<void (boost::shared_ptr<pmt::pmt_base>)> > >, pmt::comparator, std::allocator<std::pair<boost::shared_ptr<pmt::pmt_base> const, boost::function<void (boost::shared_ptr<pmt::pmt_base>)> > > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<boost::shared_ptr<pmt::pmt_base> const&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<boost::shared_ptr<pmt::pmt_base> const, boost::function<void (boost::shared_ptr<pmt::pmt_base>)> > >, std::piecewise_construct_t const&, std::tuple<boost::shared_ptr<pmt::pmt_base> const&>&&, std::tuple<>&&)':
main.cpp:(.text._ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJRS6_EESK_IJEEEEESt17_Rb_tree_iteratorISA_ESt23_Rb_tree_const_iteratorISA_EDpOT_[_ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJRS6_EESK_IJEEEEESt17_Rb_tree_iteratorISA_ESt23_Rb_tree_const_iteratorISA_EDpOT_]+0x70): undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: main.cpp:(.text._ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJRS6_EESK_IJEEEEESt17_Rb_tree_iteratorISA_ESt23_Rb_tree_const_iteratorISA_EDpOT_[_ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJRS6_EESK_IJEEEEESt17_Rb_tree_iteratorISA_ESt23_Rb_tree_const_iteratorISA_EDpOT_]+0x84): undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: main.cpp:(.text._ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJRS6_EESK_IJEEEEESt17_Rb_tree_iteratorISA_ESt23_Rb_tree_const_iteratorISA_EDpOT_[_ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJRS6_EESK_IJEEEEESt17_Rb_tree_iteratorISA_ESt23_Rb_tree_const_iteratorISA_EDpOT_]+0xbe): undefined reference to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)'
/usr/bin/ld: /tmp/ccg47hpw.o:main.cpp:(.text._ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJRS6_EESK_IJEEEEESt17_Rb_tree_iteratorISA_ESt23_Rb_tree_const_iteratorISA_EDpOT_[_ZNSt8_Rb_treeIN5boost10shared_ptrIN3pmt8pmt_baseEEESt4pairIKS4_NS0_8functionIFvS4_EEEESt10_Select1stISA_ENS2_10comparatorESaISA_EE22_M_emplace_hint_uniqueIJRKSt21piecewise_construct_tSt5tupleIJRS6_EESK_IJEEEEESt17_Rb_tree_iteratorISA_ESt23_Rb_tree_const_iteratorISA_EDpOT_]+0x159): more undefined references to `pmt::eqv(boost::shared_ptr<pmt::pmt_base> const&, boost::shared_ptr<pmt::pmt_base> const&)' follow
/usr/bin/ld: /tmp/ccg47hpw.o:(.data.rel.ro._ZTV12scanner_sink[_ZTV12scanner_sink]+0x20): undefined reference to `gr::msg_accepter::post(boost::shared_ptr<pmt::pmt_base>, boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: /tmp/ccg47hpw.o:(.data.rel.ro._ZTV12scanner_sink[_ZTV12scanner_sink]+0x80): undefined reference to `gr::block::set_log_level(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: /tmp/ccg47hpw.o:(.data.rel.ro._ZTV12scanner_sink[_ZTV12scanner_sink]+0x88): undefined reference to `gr::block::log_level[abi:cxx11]()'
/usr/bin/ld: /tmp/ccg47hpw.o:(.data.rel.ro._ZTV8TopBlock[_ZTV8TopBlock]+0x20): undefined reference to `gr::msg_accepter::post(boost::shared_ptr<pmt::pmt_base>, boost::shared_ptr<pmt::pmt_base>)'
/usr/bin/ld: /tmp/ccg47hpw.o:(.data.rel.ro._ZTV8TopBlock[_ZTV8TopBlock]+0x80): undefined reference to `gr::hier_block2::set_log_level(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/bin/ld: /tmp/ccg47hpw.o:(.data.rel.ro._ZTV8TopBlock[_ZTV8TopBlock]+0x88): undefined reference to `gr::hier_block2::log_level[abi:cxx11]()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:35: gr-scan] Error 1
```

Any help, suggestions, pointers, etc. is greatly appreciated.
Thank you in advance!

**Comment by AndrewBarfield** [comment]
Yep! That was it. I removed gnuradio, gqrx, etc., etc. and reinstalled using:
```
sudo apt-get install gnuradio gr-osmosdr gr-gsm
```
I was able to compile just fine:
```
drew@hadescanyonnuc:~/Projects/SDR/gr-sigar$ make
g++  -O3 -march=native -fomit-frame-pointer -DVERSION="\"gr-scan 20180115\"" -Wall -std=c++11 *.cpp -o gr-scan -llog4cpp -lgnuradio-filter -lgnuradio-blocks -lgnuradio-pmt -lgnuradio-fft -lgnuradio-runtime -lgnuradio-osmosdr -lboost_system -lstdc++fs 
```
I got this on my first run:
```
drew@hadescanyonnuc:~/Projects/SDR/gr-sigar$ ./gr-scan
gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.13.4
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
[INFO] [UHD] linux; GNU C++ version 8.3.0; Boost_106700; UHD_3.13.1.0-3build1

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,10), Device or resource busy.

Using HackRF One with firmware 2018.01.1 
gr::buffer::allocate_buffer: warning: tried to allocate
   4 items of size 16000. Due to alignment requirements
   32 were allocated.  If this isn't OK, consider padding
   your structure to a power-of-two bytes.
   On this platform, our allocation granularity is 4096 bytes.
gr::buffer::allocate_buffer: warning: tried to allocate
   16 items of size 8000. Due to alignment requirements
   64 were allocated.  If this isn't OK, consider padding
   your structure to a power-of-two bytes.
   On this platform, our allocation granularity is 4096 bytes.
gr::buffer::allocate_buffer: warning: tried to allocate
   8 items of size 8000. Due to alignment requirements
   64 were allocated.  If this isn't OK, consider padding
   your structure to a power-of-two bytes.
   On this platform, our allocation granularity is 4096 bytes.
gr::buffer::allocate_buffer: warning: tried to allocate
   8 items of size 8000. Due to alignment requirements
   64 were allocated.  If this isn't OK, consider padding
   your structure to a power-of-two bytes.
   On this platform, our allocation granularity is 4096 bytes.

00:00:01: Finished scanning 86.000000 MHz - 88.000000 MHz
00:00:02: Finished scanning 86.500000 MHz - 88.500000 MHz
[+] 00:00:02: Found signal: at 87.098000 MHz of width 40.000000 kHz, peak power -50.568214 dB (difference 3.435036 dB) 
00:00:03: Finished scanning 87.000000 MHz - 89.000000 MHz
00:00:04: Finished scanning 87.500000 MHz - 89.500000 MHz
[+] 00:00:04: Found signal: at 88.311500 MHz of width 63.000000 kHz, peak power -52.125710 dB (difference 3.952995 dB) 
[+] 00:00:04: Found signal: at 88.704000 MHz of width 80.000000 kHz, peak power -49.968948 dB (difference 3.547493 dB) 
[+] 00:00:04: Found signal: at 89.098500 MHz of width 25.000000 kHz, peak power -39.693859 dB (difference 10.222668 dB) 
00:00:05: Finished scanning 88.000000 MHz - 90.000000 MHz
[+] 00:00:05: Found signal: at 89.485000 MHz of width 60.000000 kHz, peak power -44.795727 dB (difference 5.251339 dB) 
[+] 00:00:05: Found signal: at 89.602000 MHz of width 32.000000 kHz, peak power -45.628517 dB (difference 4.900608 dB) 
00:00:06: Finished scanning 88.500000 MHz - 90.500000 MHz
[+] 00:00:06: Found signal: at 89.990500 MHz of width 61.000000 kHz, peak power -46.420532 dB (difference 4.416855 dB) 
[+] 00:00:06: Found signal: at 90.278000 MHz of width 64.000000 kHz, peak power -47.064556 dB (difference 3.186626 dB) 
00:00:07: Finished scanning 89.000000 MHz - 91.000000 MHz
[+] 00:00:07: Found signal: at 90.704500 MHz of width 63.000000 kHz, peak power -35.932430 dB (difference 6.902988 dB) 
00:00:08: Finished scanning 89.500000 MHz - 91.500000 MHz
[+] 00:00:08: Found signal: at 91.197000 MHz of width 104.000000 kHz, peak power -43.233414 dB (difference 3.288982 dB) 
00:00:09: Finished scanning 90.000000 MHz - 92.000000 MHz
00:00:10: Finished scanning 90.500000 MHz - 92.500000 MHz
[+] 00:00:10: Found signal: at 92.283500 MHz of width 57.000000 kHz, peak power -38.165318 dB (difference 4.002922 dB) 
00:00:11: Finished scanning 91.000000 MHz - 93.000000 MHz
[+] 00:00:11: Found signal: at 91.907500 MHz of width 109.000000 kHz, peak power -42.216137 dB (difference 3.466068 dB) 
[+] 00:00:11: Found signal: at 92.707000 MHz of width 104.000000 kHz, peak power -36.401993 dB (difference 4.195927 dB) 
00:00:12: Finished scanning 91.500000 MHz - 93.500000 MHz
[+] 00:00:12: Found signal: at 92.807000 MHz of width 88.000000 kHz, peak power -44.357658 dB (difference 3.124447 dB) 
[+] 00:00:12: Found signal: at 93.090500 MHz of width 43.000000 kHz, peak power -39.014606 dB (difference 6.197037 dB) 
[+] 00:00:12: Found signal: at 93.214500 MHz of width 65.000000 kHz, peak power -41.402645 dB (difference 3.729630 dB) 
00:00:13: Finished scanning 92.000000 MHz - 94.000000 MHz
[+] 00:00:13: Found signal: at 93.582000 MHz of width 84.000000 kHz, peak power -41.447231 dB (difference 3.815498 dB) 
00:00:14: Finished scanning 92.500000 MHz - 94.500000 MHz
[+] 00:00:14: Found signal: at 94.286500 MHz of width 51.000000 kHz, peak power -33.868774 dB (difference 5.652489 dB) 
00:00:15: Finished scanning 93.000000 MHz - 95.000000 MHz
00:00:16: Finished scanning 93.500000 MHz - 95.500000 MHz
[+] 00:00:16: Found signal: at 94.893500 MHz of width 99.000000 kHz, peak power -35.327297 dB (difference 3.219349 dB) 
00:00:17: Finished scanning 94.000000 MHz - 96.000000 MHz
00:00:18: Finished scanning 94.500000 MHz - 96.500000 MHz
[+] 00:00:18: Found signal: at 96.288500 MHz of width 47.000000 kHz, peak power -33.522026 dB (difference 5.758709 dB) 
00:00:19: Finished scanning 95.000000 MHz - 97.000000 MHz
[+] 00:00:19: Found signal: at 95.390500 MHz of width 63.000000 kHz, peak power -40.376957 dB (difference 3.922672 dB) 
[+] 00:00:19: Found signal: at 95.500000 MHz of width 38.000000 kHz, peak power -40.747562 dB (difference 5.200031 dB) 
00:00:20: Finished scanning 95.500000 MHz - 97.500000 MHz
[+] 00:00:20: Found signal: at 95.999000 MHz of width 34.000000 kHz, peak power -47.449787 dB (difference 4.753868 dB) 
[+] 00:00:20: Found signal: at 96.699500 MHz of width 107.000000 kHz, peak power -41.265850 dB (difference 3.666370 dB) 
[+] 00:00:20: Found signal: at 96.899000 MHz of width 62.000000 kHz, peak power -45.424667 dB (difference 4.593491 dB) 
00:00:21: Finished scanning 96.000000 MHz - 98.000000 MHz
[+] 00:00:21: Found signal: at 96.357000 MHz of width 52.000000 kHz, peak power -50.251057 dB (difference 3.476410 dB) 
[+] 00:00:21: Found signal: at 97.501000 MHz of width 42.000000 kHz, peak power -49.525963 dB (difference 3.412518 dB) 
00:00:22: Finished scanning 96.500000 MHz - 98.500000 MHz
[+] 00:00:22: Found signal: at 97.100500 MHz of width 69.000000 kHz, peak power -42.824627 dB (difference 5.076870 dB) 
00:00:23: Finished scanning 97.000000 MHz - 99.000000 MHz
[+] 00:00:23: Found signal: at 98.488500 MHz of width 85.000000 kHz, peak power -49.926220 dB (difference 3.660736 dB) 
[+] 00:00:23: Found signal: at 98.649000 MHz of width 42.000000 kHz, peak power -48.675003 dB (difference 3.858799 dB) 
00:00:24: Finished scanning 97.500000 MHz - 99.500000 MHz
[+] 00:00:24: Found signal: at 98.704000 MHz of width 60.000000 kHz, peak power -45.954292 dB (difference 5.082088 dB) 
[+] 00:00:24: Found signal: at 99.102000 MHz of width 34.000000 kHz, peak power -36.435432 dB (difference 8.577572 dB) 
00:00:25: Finished scanning 98.000000 MHz - 100.000000 MHz
[+] 00:00:25: Found signal: at 99.593500 MHz of width 51.000000 kHz, peak power -41.285786 dB (difference 6.617580 dB) 
00:00:26: Finished scanning 98.500000 MHz - 100.500000 MHz
00:00:27: Finished scanning 99.000000 MHz - 101.000000 MHz
00:00:28: Finished scanning 99.500000 MHz - 101.500000 MHz
[+] 00:00:28: Found signal: at 101.102500 MHz of width 47.000000 kHz, peak power -37.825405 dB (difference 8.111511 dB) 
00:00:29: Finished scanning 100.000000 MHz - 102.000000 MHz
[+] 00:00:29: Found signal: at 100.939500 MHz of width 51.000000 kHz, peak power -51.718697 dB (difference 3.118076 dB) 
[+] 00:00:29: Found signal: at 101.601000 MHz of width 72.000000 kHz, peak power -45.409061 dB (difference 4.648640 dB) 
00:00:30: Finished scanning 100.500000 MHz - 102.500000 MHz
00:00:31: Finished scanning 101.000000 MHz - 103.000000 MHz
[+] 00:00:31: Found signal: at 101.498500 MHz of width 33.000000 kHz, peak power -48.333740 dB (difference 5.373028 dB) 
00:00:32: Finished scanning 101.500000 MHz - 103.500000 MHz
[+] 00:00:32: Found signal: at 101.997000 MHz of width 36.000000 kHz, peak power -49.541786 dB (difference 5.258808 dB) 
[+] 00:00:32: Found signal: at 103.235500 MHz of width 47.000000 kHz, peak power -49.413544 dB (difference 4.725681 dB) 
00:00:33: Finished scanning 102.000000 MHz - 104.000000 MHz
[+] 00:00:33: Found signal: at 103.500000 MHz of width 28.000000 kHz, peak power -38.629002 dB (difference 12.450554 dB) 
00:00:34: Finished scanning 102.500000 MHz - 104.500000 MHz
[+] 00:00:34: Found signal: at 103.733000 MHz of width 64.000000 kHz, peak power -52.724598 dB (difference 3.190502 dB) 
[+] 00:00:34: Found signal: at 104.001000 MHz of width 36.000000 kHz, peak power -44.174519 dB (difference 7.611610 dB) 
00:00:35: Finished scanning 103.000000 MHz - 105.000000 MHz
[+] 00:00:35: Found signal: at 103.289000 MHz of width 70.000000 kHz, peak power -40.132763 dB (difference 6.038273 dB) 
00:00:36: Finished scanning 103.500000 MHz - 105.500000 MHz
[+] 00:00:36: Found signal: at 105.285000 MHz of width 48.000000 kHz, peak power -36.066868 dB (difference 6.143082 dB) 
00:00:37: Finished scanning 104.000000 MHz - 106.000000 MHz
00:00:38: Finished scanning 104.500000 MHz - 106.500000 MHz
00:00:39: Finished scanning 105.000000 MHz - 107.000000 MHz
[+] 00:00:39: Found signal: at 105.893500 MHz of width 103.000000 kHz, peak power -33.473244 dB (difference 4.034077 dB) 
[+] 00:00:39: Found signal: at 106.410500 MHz of width 129.000000 kHz, peak power -34.978638 dB (difference 3.541706 dB) 
00:00:40: Finished scanning 105.500000 MHz - 107.500000 MHz
[+] 00:00:40: Found signal: at 107.288500 MHz of width 41.000000 kHz, peak power -37.427052 dB (difference 5.133240 dB) 
00:00:41: Finished scanning 106.000000 MHz - 108.000000 MHz
00:00:42: Finished scanning 106.500000 MHz - 108.500000 MHz
[+] 00:00:42: Found signal: at 107.098500 MHz of width 87.000000 kHz, peak power -48.985554 dB (difference 3.470318 dB) 
[+] 00:00:42: Found signal: at 107.908500 MHz of width 75.000000 kHz, peak power -43.995045 dB (difference 4.460312 dB) 
00:00:43: Finished scanning 107.000000 MHz - 109.000000 MHz
[+] 00:00:43: Found signal: at 107.823500 MHz of width 47.000000 kHz, peak power -49.150654 dB (difference 4.446262 dB) 
[+] 00:00:43: Found signal: at 108.411500 MHz of width 97.000000 kHz, peak power -49.571152 dB (difference 3.137703 dB) 
[*] Finished scanning
terminate called after throwing an instance of 'boost::thread_interrupted'
Aborted (core dumped)
```

Awesome!!!
